### ISSUE TITLE
Support for node style module resolution in Less

### ISSUE THREAD

**Issue by andypillip** [dependents/node-dependency-tree#109]
Awesome tool, we'd like to visualise our LESS dependencies.

Unfortunately we use the ~ notation to use node style imports within less, which are supported thanks to `less-loader`:

    @import '~antd/lib/style/color/colors';

This gets resolved to the closest node module with the name of _antd_.

It seems like node-dependency-tree is not able to resolve those imports.

**Comment by mrjoelkemp** [comment]
Hey! Not sure if you still need or want this. If you did want it, you can see from https://github.com/dependents/node-filing-cabinet/blob/74185e06edbbcbb3062265946adbada9b5584999/index.js#L34 that less files are currently using a sass file resolution algorithm for convenience. If you wanted proper Less resolution, you'd need to roll a resolver like https://github.com/dependents/node-sass-lookup but for Less. 

We could then plug that info filing-cabinet for Less resolution and then it'll just work in dependency-tree. I don't think you need a custom detective for the tilde, since detective-less (https://github.com/Mike-Dax/node-detective-less/blob/master/index.js) should be fine with just the `@import ` by itself. 

Will close for now since this is old, but happy to review a PR and provide more guidance if you wanted to contribute a PR. Cheers!
